# Generated by Django 4.1.2 on 2022-10-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('date', models.TextField()),
                ('userName', models.CharField(default=1, max_length=200)),
            ],
        ),
    ]
